# Generated by Django 3.2.4 on 2021-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='large_feature',
        ),
        migrations.RemoveField(
            model_name='post',
            name='small_feature',
        ),
        migrations.AddField(
            model_name='post',
            name='carousel_feature',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10),
        ),
    ]
