# Generated by Django 3.2.4 on 2021-07-22 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210722_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='carousel_feature',
            new_name='add_to_carousel',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10),
        ),
    ]
