# Generated by Django 3.2.4 on 2021-07-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210706_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='google_image_search',
        ),
    ]
