# Generated by Django 3.2.4 on 2021-07-27 11:51

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content_2',
            field=djrichtextfield.models.RichTextField(default='Content'),
            preserve_default=False,
        ),
    ]
