# Generated by Django 3.2.4 on 2021-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210709_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='thoughts',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
