# Generated by Django 3.2.4 on 2021-07-27 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210727_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_caption',
        ),
    ]
