# Generated by Django 3.2.4 on 2021-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210709_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=10),
        ),
    ]
