# Generated by Django 3.2.4 on 2021-07-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210709_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('not-featured', '--'), ('featured', 'Featured')], default='not-featured', max_length=12),
        ),
    ]
