# Generated by Django 3.2.4 on 2021-07-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='featured',
            new_name='featured_big',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
