# Generated by Django 3.2.4 on 2021-07-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20210709_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_big',
        ),
        migrations.AddField(
            model_name='post',
            name='featured_large',
            field=models.CharField(choices=[('not-featured', '--'), ('featured_large', 'Large Feature')], default='not-featured', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
