# Generated by Django 3.2.4 on 2021-07-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210709_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_small_1',
        ),
        migrations.AlterField(
            model_name='post',
            name='featured_large',
            field=models.CharField(choices=[('featured_small_1', 'Small Feature 1'), ('featured_large', 'Large Feature'), ('not-featured', '--')], default='not-featured', max_length=20),
        ),
    ]
