# Generated by Django 3.2.4 on 2021-07-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20210709_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='featured_large',
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.CharField(choices=[('not-featured', '--'), ('featured_large', 'Large Feature'), ('featured_small_1', 'Small Feature 1')], default='not-featured', max_length=20),
        ),
    ]
