# Generated by Django 3.2.4 on 2021-07-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20210709_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='small_feature',
            field=models.BooleanField(default=False),
        ),
    ]
