# Generated by Django 3.2.4 on 2021-07-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_post_small_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='small_feature',
            new_name='small_feature_1',
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10),
        ),
    ]
