# Generated by Django 3.2.4 on 2021-07-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210709_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='small_feature_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
    ]
